### PR TITLE
Fix Warning: Undefined array key "inputType"

### LINKED ISSUE #6: ErrorException Warning: Undefined array key "inputType"
- Contao: 4.13.5
- PHP: 8.1
- DEV-Mode

```
Warning: Undefined array key "inputType"

  at vendor/menatwork/contao-multicolumnwizard-bundle/src/Contao/Widgets/MultiColumnWizard.php:776
  at MenAtWork\MultiColumnWizardBundle\Contao\Widgets\MultiColumnWizard->generate()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:652)
  at Contao\Widget->generateWithError(true)
     (vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5:3)
  at include('/demo_isotope/vendor/contao/core-bundle/src/Resources/contao/templates/backend/be_widget.html5')
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/TemplateInheritance.php:108)
  at Contao\Widget->inherit()
     (vendor/contao/core-bundle/src/Resources/contao/library/Contao/Widget.php:599)
  at Contao\Widget->parse()
     (vendor/contao/core-bundle/src/Resources/contao/classes/DataContainer.php:784)
  at Contao\DataContainer->row('            {name_legend},name,label,fallback;            {address_legend:hide},firstname,lastname,company,vat_no,street_1,street_2,street_3,postal,city,country,subdivision,email,phone;            {bank_legend:hide},bankName,bankAccount,bankCode,taxNumber;            {checkout_legend},address_fields,billing_country,shipping_country,billing_countries,shipping_countries,limitMemberCountries,vatNoValidators;            {pricing_legend},priceDisplay,currencyFormat,priceRoundPrecision,priceRoundIncrement;            {currency_legend},currency,currencyPosition,currencySymbol,[currencySymbol],currencySpace,[EOF];            {converter_legend:hide},priceCalculateFactor,priceCalculateMode,currencyAutomator;            {order_legend:hide},orderPrefix,orderDigits,orderstatus_new,orderstatus_error,orderDetailsModule;            {config_legend},templateGroup,cartMinSubtotal;            {products_legend},newProductPeriod;            {analytics_legend},ga_enable')
     (vendor/contao/core-bundle/src/Resources/contao/drivers/DC_Table.php:1946)
  at Contao\DC_Table->edit()
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php:225)
  at Isotope\BackendModule\BackendOverview->getModule('configs')
     (vendor/isotope/isotope-core/system/modules/isotope/library/Isotope/BackendModule/BackendOverview.php:81)
  at Isotope\BackendModule\BackendOverview->generate()
     (vendor/contao/core-bundle/src/Resources/contao/classes/Backend.php:442)
  at Contao\Backend->getBackendModule('iso_setup', null)
     (vendor/contao/core-bundle/src/Resources/contao/controllers/BackendMain.php:168)
  at Contao\BackendMain->run()
     (vendor/contao/core-bundle/src/Controller/BackendController.php:49)
  at Contao\CoreBundle\Controller\BackendController->mainAction()
     (vendor/symfony/http-kernel/HttpKernel.php:152)
  at Symfony\Component\HttpKernel\HttpKernel->handleRaw(object(Request), 1)
     (vendor/symfony/http-kernel/HttpKernel.php:74)
  at Symfony\Component\HttpKernel\HttpKernel->handle(object(Request), 1, true)
     (vendor/symfony/http-kernel/Kernel.php:202)
  at Symfony\Component\HttpKernel\Kernel->handle(object(Request))
     (public/index.php:44)     
```

see: https://github.com/isotope/core/issues/2317#issuecomment-1174678674

### PR DESCRIPTION
**Pull request by ameotoko**
Fixes #6

### CODE REVIEW

File: src/Contao/Widgets/MultiColumnWizard.php [hunk 1]
```diff
@@ -772,10 +772,6 @@ public function generate($overwriteRowCurrentRow = null, $onlyRows = false)
 
                 $arrTinyMCE[] = $strKey;
             }
-
-            if ($arrField['inputType'] == 'hidden') {
```
Comment (aschempp) [inline src/Contao/Widgets/MultiColumnWizard.php:776]: is this change related to the array key warning?

Comment (ameotoko) [reply src/Contao/Widgets/MultiColumnWizard.php:776]: Do you mean, deleting instead of null-check? This block obviously doesn't do anything. I checked a few levels of changes using `blame`, and it seems this check is a forgotten leftover, that lost its purpose after refactoring. It was not previously at the end of `foreach` cycle.

Since it does contribute to the title problem, I think yes, it is related.
